### PR TITLE
Fixing SideMenu alignment Issue

### PR DESCRIPTION
**Pull request by anoopadvaitha**
Fixes issue with SideMenu Alignment.
Please let me know if you need more details.

### CODE REVIEW

**Comment by anoopadvaitha** [comment]
@lumjjb : I've fixed the issue in SideMenu. Please let me know your inputs.

**Comment by anoopadvaitha** [comment]
Comparison:
**Before** :
image
**After** : 
image

**Comment by lumjjb** [comment]
Awesome - thanks @anoopadvaitha. @mtverraen , wana do a quick review of this and then merge it!

**Review by mtverraen — APPROVED** [review]
Sidebar looks much better now! 😄

**Pull request merged**
